project:
  type: book

book:
  title: "Supplementary Materials"
  date: now
  chapters:
    - index.qmd
    - flowcyto-growth-and-biofilm-formation.qmd
    - FEAST.qmd
    - plot-tree.qmd
    - alpha-diversity.qmd
    - shannon-index.qmd
    - gsea-zzs.qmd
    - beta-diversity.qmd
    - convergence.qmd
    - contrast.qmd
    - slr-analysis.qmd
    - picrust2.qmd    


format:
  html:
    theme: cosmo
