
# 群落结构

## 加载需要的包

```{r, message=FALSE}
library(phyloseq)
library(tidytree)
library(Biostrings)
library(vegan)
library(ggtree)
library(ape)
library(scales)
library(tidyverse)
library(patchwork)
library(RColorBrewer)
library(ggVennDiagram)
library(ggpmisc)
library(export)
library(aplot)
library(cowplot)
```

### 加载数据集


```{r}
physeq <- readRDS("./data/dada2/microplate/filtered/physeq.rds") 
top10_genus_colors <- readRDS(file = "./data/dada2/microplate/top10_genus_colors.rds")
my_colors <- readRDS("./data/dada2/microplate/factor_colors.rds")
```

## 初始细胞数促群落结构


### 计算


```{r}
theme_set(theme_bw())

ps_genus <- tax_glom(physeq, "Genus")
ps_relabund <- transform_sample_counts(ps_genus, function(x) x / sum(x, na.rm = TRUE))
df_all <- psmelt(ps_relabund) |> as_tibble()

top10_genus_all <- df_all %>%
  group_by(Genus) %>%
  summarise(total = sum(Abundance), .groups="drop") %>%
  slice_max(order_by = total, n = 7) %>%
  pull(Genus)

```

### 不同碳源

```{r}
df_summary <- df_all %>% 
  mutate(Genus = fct_relevel(fct_other(Genus, top10_genus_all), c(top10_genus_all, "Other")),
         cell_num = as_factor(cell_num)) |> 
  group_by(carbon, cell_num, Genus) |> 
  summarise(Abundance = mean(Abundance), .groups = "drop")

p = ggplot(df_summary, aes(x = cell_num, y = Abundance, fill = Genus)) +
  geom_bar(
    stat = "identity",
    position = position_fill(reverse = FALSE)
  ) +
  facet_wrap(~carbon, nrow = 1) +
  scale_y_continuous(
    labels = scales::label_percent(), 
    expand = c(0, 0)
  ) +
  scale_fill_manual(
    values = top10_genus_colors,
    name = "Genus",
    guide = guide_legend(reverse = F) 
  ) +
  labs(
    x = NULL,
    y = "Relative Abundance"
  ) +
  theme(
    legend.position = "right" ,
    axis.text.x = element_text( size = 10),
    aspect.ratio = 1.2
  )

p

```

### 不同处理


```{r}
#| fig-width: 10
#| fig-height: 10

sample_order = df_all %>%
  filter(Genus == "Pseudomonas") %>%
  arrange(desc(Abundance)) %>%
  pull(Sample) %>%
  as.character()

df_mod = df_all |> 
  mutate(Genus = fct_relevel(fct_other(Genus, top10_genus_all), c(top10_genus_all, "Other")),
         cell_num = as_factor(cell_num)) |> 
  group_by(carbon, cell_num, Sample, Genus) |>
  summarise(Abundance = sum(Abundance, na.rm = TRUE), .groups = "drop") |> 
  mutate(Sample = fct_relevel(Sample, sample_order))

p = ggplot(df_mod, aes(Sample, Abundance, fill = Genus)) +
  geom_bar(stat = "identity", 
           position = position_fill(reverse = TRUE),
           width = 1) +
  scale_fill_manual(values = top10_genus_colors) +
  scale_y_continuous(name = "Relative Abundance",labels = scales::label_percent()) +
  facet_wrap(~ carbon + cell_num, scales = "free_x") +
  theme(
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        element_text(angle = 30, hjust = 1, size = 10)
        )
p
```

### 整体群落结构


```{r}
p <- ggplot(df_mod, aes(Sample, Abundance, fill = Genus)) +
  geom_bar(stat = "identity", position = position_fill(reverse = TRUE), width = 1) +
  scale_fill_manual(
    values = top10_genus_colors,  
    name = "Genus",
    guide = guide_legend(reverse = FALSE)  
  ) +
  scale_y_continuous(labels = scales::label_percent(), expand = expansion(0, 0.01)) +
  scale_x_discrete(expand = c(0, 0)) + 
  labs(x = NULL, y = "Relative Abundance") +
  theme(
    legend.position = "none",
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )


sample_info <- data.frame(sample_data(physeq)) |> 
  mutate(
    sampleID = fct_relevel(as.character(sampleID), sample_order),
    cell_num = as_factor(cell_num),
    carbon   = as_factor(carbon),
    class    = as_factor(class)
  ) |> 
  as_tibble()


metrics <- c("carbon", "cell_num", "class")
color_keys <- c("carbon", "cell", "class") 

plots <- lapply(seq_along(metrics), function(i) {
  var_name <- metrics[i]
  col_key <- color_keys[i]
  
  ggplot(sample_info, aes(x = sampleID, y = var_name, fill = .data[[var_name]])) +
    geom_tile() +
    scale_fill_manual(values = my_colors[[col_key]]) + 
    scale_y_discrete(expand = expansion(0, 0)) +
    labs(fill = var_name) +
    theme(
      legend.position = "none",
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    )
})

main_panel <- purrr::reduce(plots, insert_bottom) |> 
  insert_top(p, height = 18)

main_legend <- (p + 
  guides(fill = guide_legend(nrow = 4, title = "Genus")) + 
  theme(legend.position = "right")) |> 
  get_legend()

metric_legends <- lapply(plots, function(x) get_legend(x + theme(legend.position = "right")))
blank <- ggplot() + theme_void()

legend_panel <- wrap_plots(
  blank,
  main_legend, 
  metric_legends[[1]], 
  metric_legends[[2]], 
  metric_legends[[3]], 
  nrow = 1
) + plot_layout(widths = c(0.3, 9, 1.8, 1.5, 1.5))

final_plot <- wrap_plots(as.patchwork(main_panel), legend_panel, ncol = 1) + 
  plot_layout(heights = c(4, 3))

print(final_plot)
```

