
# β多样性分析

## 加载包

```{r}
library(phyloseq)  
library(ggplot2)
library(ggpubr)
library(ggVennDiagram)
library(cowplot)
library(glue)
library(export)
library(vegan)
library(pairwiseAdonis)
theme_set(theme_bw())
```

## 读取数据集

```{r}
physeq <- readRDS("./data/dada2/microplate/filtered/physeq.rds") 
my_saved_colors <- readRDS("./data/dada2/microplate/factor_colors.rds" )
```

### 绘图准备

```{r}
carbon_levels <- sample_data(physeq)[["carbon"]] |> unique() |> sort()
cell_num_levels <- sample_data(physeq)[["cell_num"]] |> unique() |> sort()
```

## 不同碳源ASV

```{r}
#| label: fig-asv-overlapping-by-carbon

data_list = lapply(carbon_levels, function(this_carbon){
  meta = as(sample_data(physeq), "data.frame")
  keep_id = rownames(meta[meta$carbon == this_carbon, ])
  ps_sub = prune_samples(keep_id, physeq)
  ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub) 
  taxa_names(ps_final)
})
names(data_list) = carbon_levels

p = ggVennDiagram(data_list, label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "firebrick") +
  scale_x_continuous(expand = expansion(0.1))

p
```


## 不同细胞数ASV

```{r}
#| label: fig-asv-overlapping-by-cellnum

data_list = lapply(cell_num_levels, function(this){
  meta = as(sample_data(physeq), "data.frame")
  keep_id = rownames(meta[meta$cell_num == this, ])
  ps_sub = prune_samples(keep_id, physeq)
  ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
  taxa_names(ps_final)
})

names(data_list) = cell_num_levels

p = ggVennDiagram(data_list, label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "firebrick") +
  scale_x_continuous(expand = expansion(0.1)) +
  theme(legend.position = "none")

p

```


## 综合考虑碳源和初始细胞数

```{r}
#| label: fig-asv-overlapping-by-carbon-and-cellnum

plots = lapply(carbon_levels, function(this_carbon){
  data_list = lapply(cell_num_levels, function(this_cell_num){
    meta = as(sample_data(physeq), "data.frame")
    keep_id = rownames(meta[meta$carbon == this_carbon & meta$cell_num == this_cell_num, ])
    ps_sub = prune_samples(keep_id, physeq)
    ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
    taxa_names(ps_final)
  })
  names(data_list) = cell_num_levels
  p = ggVennDiagram(data_list, label = "count", label_alpha = 0) +
    scale_fill_gradient(low = "white", high = "firebrick", limits = c(0, 60)) +
    labs(title = this_carbon) +
    theme(legend.position = "none",
          plot.title = element_text(hjust = 0.5))
  return(p)
})

p = cowplot::plot_grid(plotlist = plots, labels = "auto")

p

```

```{r}
meta_df = as(sample_data(physeq), "data.frame")
plots = lapply(cell_num_levels, function(this_cell_num){
  data_list = lapply(carbon_levels, function(this_carbon){
    keep_id = rownames(meta_df[meta_df$carbon == this_carbon & meta_df$cell_num == this_cell_num, ])
    ps_sub = prune_samples(keep_id, physeq)
    ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
    taxa_names(ps_final)
  })
  names(data_list) = carbon_levels
  p = ggVennDiagram(data_list, label = "count", label_alpha = 0) +
    scale_fill_gradient(low = "white", high = "firebrick", limits = c(0, 60)) +
    labs(title = paste("", this_cell_num)) + 
    theme(legend.position = "none",
          plot.title = element_text(hjust = 0.5, face = "bold"))
  return(p)
})

p = cowplot::plot_grid(plotlist = plots, labels = "auto")

print(p)
```


##  不同初始细胞数分组之间微生物群落结构存在显著差异

### 群落β多样性绘制函数

```{r}
plot_pcoa_res = function(physeq, group_var = "cell_num", shape_var = "carbon"){
  pcoa_res = ordinate(physeq, method = "PCoA", distance = "bray")
  dist_mat = phyloseq::distance(physeq, method = "bray")

  metadata = data.frame(sample_data(physeq))
  formula_str = as.formula(paste("dist_mat ~", group_var))
  
  set.seed(123) 
  ad_res = adonis2(formula_str, data = metadata) 

  r2_val = round(ad_res$R2[1], 3)
  p_val = ad_res$`Pr(>F)`[1]
  p_label = if(p_val < 0.001) "< 0.001" else round(p_val, 3)

  pc1_exp = round(pcoa_res$values$Relative_eig[1] * 100, 2)
  pc2_exp = round(pcoa_res$values$Relative_eig[2] * 100, 2)
  stats_label = paste0("R^2 == ", r2_val, " * ',' ~ p == ", p_label)
  plot_data = plot_ordination(physeq, pcoa_res, justDF = TRUE)

  ggplot(plot_data, aes(.data[["Axis.1"]], .data[["Axis.2"]], color = factor(.data[[group_var]]))) +
    geom_point(mapping = if(!is.null(shape_var)) aes(shape = factor(.data[[shape_var]]))) +
    stat_ellipse(aes(group = .data[[group_var]]), linetype = 2, size = 0.3, show.legend = FALSE, type = "t") +
    annotate("text", x = -Inf, y = Inf, label = stats_label, parse = TRUE,
             hjust = -0.1, vjust = 1.2, size = 3.5, fontface = "italic") +
    labs(
      x = glue("PCoA 1 ({pc1_exp}%)"), 
      y = glue("PCoA 2 ({pc2_exp}%)")
    )
}
```

### 比较细胞数

```{r}
#| label: fig-pcoa-by-carbon-and-cellnum

plots = list()
for (this_carbon in carbon_levels){
  ps_sub = subset_samples(physeq, carbon == this_carbon)
  ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
  
  p = plot_pcoa_res(ps_final, shape_var = NULL) +
    scale_color_manual(values = my_saved_colors$cell) +
    scale_y_continuous(expand = expansion(mult = 0.3)) + 
    labs(color = "cell num", subtitle = this_carbon) +
    theme(legend.position = "none", aspect.ratio = 1)
    
  plots[[this_carbon]] = p
}

legend = get_legend(plots[[1]] + theme(legend.position = "right"))
p = plot_grid(plot_grid(plotlist = plots, labels = "auto"), legend, ncol = 2, rel_widths = c(3, 0.4))

p
```

### 比较表型

```{r}
#| label: fig-pcoa-by-carbon-and-class

plots = list()
for (this_carbon in carbon_levels){
  ps_sub = subset_samples(physeq, carbon == this_carbon)
  ps_final = prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
  p = plot_pcoa_res(ps_final, group_var = "class", shape_var = NULL) +
    scale_color_manual(values = my_saved_colors$class) +
    scale_y_continuous(expand = expansion(mult = 0.3)) + 
    labs(color = "class", subtitle = this_carbon) +
    theme(legend.position = "none" ,aspect.ratio = 1)
  
  plots[[this_carbon]] = p
}

legend = get_legend(plots[[1]] + theme(legend.position = "right"))
p = plot_grid(plot_grid(plotlist = plots, labels = "auto"), legend, ncol = 2, rel_widths = c(3, 0.4))

p
```

### 比较碳源

```{r}
#| label: fig-pcoa-carbon-within-cellnum

cell_num_levels <- sort(unique(
  as.numeric(as.character(sample_data(physeq)$cell_num))
))
plots <- list()
for (this_cell_num in cell_num_levels) {
  ps_sub <- subset_samples(
    physeq,
    as.numeric(as.character(cell_num)) == this_cell_num)
  
  ps_final <- prune_taxa(taxa_sums(ps_sub) > 0, ps_sub)
  p <- plot_pcoa_res(ps_final,group_var = "carbon",shape_var = NULL) +
    scale_color_manual(values = my_saved_colors$carbon) +
    scale_y_continuous(expand = expansion(mult = 0.3)) +
    labs(color = "carbon",subtitle = paste0("cell num: ", this_cell_num)) +
    theme(legend.position = "none",aspect.ratio = 1)
  plots[[as.character(this_cell_num)]] <- p
}

legend <- get_legend(plots[[1]] +theme(legend.position = "right"))

p <- plot_grid(plot_grid(plotlist = plots, labels = "auto"),legend,ncol = 2,rel_widths = c(3, 0.4))

p

```


