
# 生物量生物膜样品选择

## 加载需要的包

```{r}
library(tidyverse)
library(ggpubr)
library(dunn.test)
library(multcompView)
library(MASS)
library(ggforce)
library(patchwork)
library(cowplot)
library(agricolae)
```
 
### 读取保存的数据

```{r}
all_data = read_csv("data/20240717_all_data.csv")
sample_n(all_data, 10)
```

```{r}
all_data = all_data |> 
  tidyr::unite(well_id, cell_num ,method,plate, well_position, remove = FALSE)

all_data = all_data |> 
  mutate(cell_num = factor(cell_num),
         carbon = factor(carbon))

theme_set(theme_bw())
```

## 统计分析

```{r}
growth_data = all_data |> 
  filter(measure == "growth", time == 16) |> 
  droplevels()

biofilm_data = all_data |> 
  filter(measure == "biofilm", time == 14) |> 
  droplevels()
```

### 分析初始细胞数量与生长和生物膜表型之间的关系

```{r}
plot_boxplot_with_group_letters = function(dat) {
  dat <- dat %>%
    group_by(carbon, cell_num) %>%
    dplyr::filter(! value %in% boxplot.stats(value)$out) %>%
    ungroup()
  max_value = dat |> group_by(cell_num) |> summarise(upper_whisker = boxplot.stats(value)$stats[5], .groups = "drop")
  group_letters = with(dat, kruskal(value, cell_num, p.adj="bonferroni", group=TRUE))$groups |> 
    data.frame() |>
    rownames_to_column("cell_num") |> 
    dplyr::select(cell_num, groups) |> 
    left_join(max_value, by = "cell_num")
  p.value = kruskal.test(value ~ cell_num, dat)$p.value
  p = ggplot(dat, aes(x = cell_num, y = value)) +
    geom_boxplot(outlier.shape = NA) +
    annotate("text", x = -Inf, y = Inf, label = paste0("p = ", format(p.value, digits = 2, scientific = TRUE)), vjust = 1.2, hjust = -0.2, fontface = "italic") +
    scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) +
    theme(plot.title = element_text(hjust = 0.5)) 

  if (p.value < 0.05){
    p = p + geom_text(data = group_letters, 
              aes(x = cell_num, y = upper_whisker + 0.1 * upper_whisker, label = groups)) 
  }

  return(p)
}
```

### 生长情况以及生物膜

```{r}
plots_growth = lapply(levels(growth_data$carbon), function(carb) {
  dat = growth_data %>% filter(carbon == carb)
  plot_boxplot_with_group_letters(dat) +
    labs(x = NULL, y = "Growth (OD600)", title = carb)
})



plots_biofilm = lapply(levels(biofilm_data$carbon), function(carb) {
  dat = biofilm_data %>% filter(carbon == carb)
  plot_boxplot_with_group_letters(dat) +
    labs(x = NULL, y = "Biofilm (OD595)", title = carb)
})


cowplot::plot_grid(plotlist = c(plots_growth, plots_biofilm), ncol = 4, labels = "auto")
```
### SBF矫正

```{r}
merged_data <- growth_data %>%
  dplyr::select(carbon, cell_num, well_position, growth_value = value) %>%
  inner_join(
    biofilm_data %>% dplyr::select(carbon, cell_num, well_position, biofilm_value = value),
    by = c("carbon", "cell_num", "well_position")
  ) %>%
  mutate(value = biofilm_value / growth_value) %>%
  filter(is.finite(value))

get_sbf_annotations <- function(dat) {
  anno_list <- list()
  letter_list <- list()
  
  for(carb in levels(dat$carbon)) {
    sub_dat <- dat %>% filter(carbon == carb)
    if(nrow(sub_dat) == 0) next 
    test_res <- kruskal(sub_dat$value, sub_dat$cell_num, p.adj="bonferroni", group=TRUE, console=FALSE)
    p_val <- test_res$statistics$p.chisq 
    anno_list[[carb]] <- data.frame(
      carbon = carb,
      p_label = paste0("p = ", format(p_val, digits = 2, scientific = TRUE))
    )
    
    if(p_val < 0.05) {
      max_y <- sub_dat %>%
        group_by(cell_num) %>%
        summarise(y_top = max(value), .groups = "drop") 
      letters <- test_res$groups %>%
        rownames_to_column("cell_num") %>%
        left_join(max_y, by = "cell_num") %>%
        mutate(carbon = carb)
      
      letter_list[[carb]] <- letters
    }
  }
  
  return(list(pvals = bind_rows(anno_list), letters = bind_rows(letter_list)))
}

plot_data <- merged_data %>%
  group_by(carbon, cell_num) %>%
  dplyr::filter(! value %in% boxplot.stats(value)$out) %>%
  ungroup()

sbf_anno <- get_sbf_annotations(plot_data)

p_sbf_facet <- ggplot(plot_data, aes(x = cell_num, y = value)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(~ carbon, scales = "free_y", nrow = 1) +
  geom_text(data = sbf_anno$pvals, aes(x = -Inf, y = Inf, label = p_label), 
            vjust = 1.5, hjust = -0.1, fontface = "italic", inherit.aes = FALSE) +
  geom_text(data = sbf_anno$letters, aes(x = cell_num, y = y_top * 1.1, label = groups), 
            inherit.aes = FALSE) +
  labs(x = "Initial Cell Number", y = "SBF (Biofilm / Growth)") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "gray95"),
        strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank(),
        aspect.ratio = 1)

print(p_sbf_facet)
```


## 根据生物膜和生长情况的中位数对群落进行分类

### 为剔除未生长的群落，排除了growth值不超过背景值1.25倍的样品

```{R,fig.width=9, fig.height=8}
flowcyto_normal_day14 <- all_data %>% 
  dplyr::filter(time == 16, method == "flowcyto", measure == "growth", carbon %in% c("trehalose", "mannitol", "cellobiose", "glutamic acid")) %>%
  dplyr::select(well_id, carbon, cell_num, value) %>% 
  dplyr::rename(growth = value) %>%   
  dplyr::left_join(
    all_data %>% 
      dplyr::filter(time == 14, method == "flowcyto", measure == "biofilm", carbon %in% c("trehalose", "mannitol", "cellobiose", "glutamic acid")) %>% 
      dplyr::select(well_id, carbon, cell_num, value) %>% 
      dplyr::rename(biofilm = value), 
    by = c("well_id", "carbon", "cell_num")
  )

flowcyto_normal_day14_dy0.1 <- flowcyto_normal_day14 %>% 
  dplyr::filter(growth >= 0.1) %>%
  mutate(well_id = trimws(as.character(well_id)))

edge_well_ids_suffix <- trimws(c("A1", "A2", "A3", "A4", "A5", "A6","A7", "A8", "A9", "A10", "A11", "A12",
                                 "B1", "B12", "C1", "C12", "D1", "D12", "E1", "E12", "F1", "F12",
                                 "G1", "G12", "H1", "H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10", "H11", "H12"))

flowcyto_normal_day14_dy0.1 <- flowcyto_normal_day14_dy0.1 %>%
  mutate(location = ifelse(sub(".*_", "", well_id) %in% edge_well_ids_suffix, "edge", "inside")) %>%
  dplyr::filter(location == "inside", carbon %in% c("trehalose", "mannitol", "cellobiose", "glutamic acid"))
```

### 对数据进行分类

```{R,fig.width=9, fig.height=8}
growth_lambda <- boxcox(lm(growth ~ 1, data = flowcyto_normal_day14_dy0.1), plotit = FALSE)$x[which.max(boxcox(lm(growth ~ 1, data = flowcyto_normal_day14_dy0.1), plotit = FALSE)$y)]
biofilm_lambda <- boxcox(lm(biofilm ~ 1, data = flowcyto_normal_day14_dy0.1), plotit = FALSE)$x[which.max(boxcox(lm(biofilm ~ 1, data = flowcyto_normal_day14_dy0.1), plotit = FALSE)$y)]

carbon_cell_medians <- flowcyto_normal_day14_dy0.1 %>%
  group_by(carbon, cell_num) %>%
  dplyr::summarize(
    transformed_growth_median = (median(growth, na.rm=T)^growth_lambda - 1) / growth_lambda,
    transformed_biofilm_median = (median(biofilm, na.rm=T)^biofilm_lambda - 1) / biofilm_lambda,
    transformed_growth_q1 = (quantile(growth, 0.25, na.rm=T)^growth_lambda - 1) / growth_lambda,
    transformed_growth_q3 = (quantile(growth, 0.75, na.rm=T)^growth_lambda - 1) / growth_lambda,
    transformed_biofilm_q1 = (quantile(biofilm, 0.25, na.rm=T)^biofilm_lambda - 1) / biofilm_lambda,
    transformed_biofilm_q3 = (quantile(biofilm, 0.75, na.rm=T)^biofilm_lambda - 1) / biofilm_lambda,
    .groups = 'drop'
  )

filtered_normal_day14_iqr <- flowcyto_normal_day14_dy0.1 %>%
  mutate(
    transformed_growth = (growth^growth_lambda - 1) / growth_lambda,
    transformed_biofilm = (biofilm^biofilm_lambda - 1) / biofilm_lambda
  ) %>%
  left_join(carbon_cell_medians, by = c("carbon", "cell_num")) %>%
  mutate(
    class = case_when(
      transformed_growth <= transformed_growth_median & transformed_biofilm >  transformed_biofilm_median ~ "LGHB",
      transformed_growth <= transformed_growth_median & transformed_biofilm <= transformed_biofilm_median ~ "LGLB",
      transformed_growth >  transformed_growth_median & transformed_biofilm >  transformed_biofilm_median ~ "HGHB",
      TRUE ~ "HGLB"
    ),
    dist_growth = abs(transformed_growth - transformed_growth_median),
    dist_biofilm = abs(transformed_biofilm - transformed_biofilm_median),
    iqr_growth = transformed_growth_q3 - transformed_growth_q1,
    iqr_biofilm = transformed_biofilm_q3 - transformed_biofilm_q1
  ) %>%
  filter(!(dist_growth <= 0.5 * iqr_growth / 2 | dist_biofilm <= 0.5 * iqr_biofilm / 2))
```

## 对分类后的数据进行挑选

### 读取挑选数据

```{R,fig.width=9, fig.height=8}
sequencing_data <- read_csv("./data/sequencing_data.csv") %>%
  mutate(well_id = trimws(as.character(well_id))) %>%
  separate(well_id, into = c("cell_num_part", "class_part", "plate_part", "well_part"), sep = "_") %>%
  mutate(well_id = paste(class_part, cell_num_part, plate_part, well_part, sep = "_")) %>%
  dplyr::select(well_id)

selected_samples <- filtered_normal_day14_iqr %>% inner_join(sequencing_data, by = "well_id")
```

### 对挑选的数据进行可视化

阈值设定为：
Q1（第一个四分位数）：将数据按升序排列后，25%的数据小于或等于这个值。
Q3（第三个四分位数）：将数据按升序排列后，75%的数据小于或等于这个值。
中位数：将数据按升序排列后，50%的数据小于或等于这个值。
四分位距（IQR）是通过Q3减去Q1计算，用于衡量数据的离散程度。

```{R,fig.width=9, fig.height=8}
unique_carbon <- unique(filtered_normal_day14_iqr$carbon)
plot_list <- list()

for (carbon_type in unique_carbon) {
  df_gray    <- filtered_normal_day14_iqr %>% filter(carbon == carbon_type)
  df_new     <- selected_samples          %>% filter(carbon == carbon_type)
  df_medians <- carbon_cell_medians       %>% filter(carbon == carbon_type)
  
  plot_list[[as.character(carbon_type)]] <- ggplot() +
    geom_point(data = df_gray, aes(x = transformed_growth, y = transformed_biofilm), color = "grey", size = 1, alpha = 0.5) +
    geom_point(data = df_new, aes(x = transformed_growth, y = transformed_biofilm, color = class), size = 2, shape = 16) +
    geom_vline(data = df_medians, aes(xintercept = transformed_growth_median), linetype = "dashed", color = "black") +
    geom_hline(data = df_medians, aes(yintercept = transformed_biofilm_median), linetype = "dashed", color = "black") +
    scale_color_manual(
      limits = c("LGLB", "LGHB", "HGHB", "HGLB"), 
      values = c("LGLB" = "red", "LGHB" = "blue", "HGHB" = "green", "HGLB" = "orange"), drop = FALSE
    ) +
    labs(title = carbon_type, x = "", y = "Biofilm", color = "class") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 0, hjust = 0.5)) +
    facet_wrap(~ cell_num, scales = "free")
}

row_list <- map(seq_len(ceiling(length(plot_list) / 2)), function(i) {
  wrap_plots(plot_list[min((i*2)-1, length(plot_list)):min(i*2, length(plot_list))], ncol = 2) +
    plot_layout(guides = "collect") & theme(legend.position = "right")
})

final_plot <- wrap_plots(row_list, ncol = 1) + 
  plot_annotation(tag_levels = list(c("", rep("", length(row_list) - 1)))) & 
  theme(plot.tag = element_text(size = 10, face = "bold", hjust = 45, vjust = 1))

print(final_plot)
```


