
# GSEA 分析

```{r}
library(phyloseq)
library(cailab.amplicon)
library(dplyr)
library(stringr)
library(tibble)

ps = readRDS(xfun::magic_path("microplate/filtered/physeq.rds"))

```

## 假单胞菌

```{r}
gseaRes_P = run_microbiome_gsea(
    ps, 
    taxon_target = "Pseudomonas", 
    sample_feat = c("carbon","cell_num","class"), 
    taxon_rank = "Genus")

gseaRes_P
```

```{r}
gseaRes_P |> 
  filter(str_detect(pathway, "cell_num")) |>
  mutate(pathway = factor(pathway, levels = paste("cell_num", c(10,50,100,250),sep="_"))) |>
  gsea_plot()
```

```{r}
gseaRes_P |> 
  filter(str_detect(pathway, "carbon")) |>
  gsea_plot()
```

```{r}
gseaRes_P |> 
  filter(str_detect(pathway, "class")) |>
  gsea_plot()
```

```{r}
gsea_plot_all(gseaRes_P, ncol = 2)
```

## 克雷伯氏菌

```{r}
gseaRes_K = run_microbiome_gsea(
    ps, 
    taxon_target = "Klebsiella", 
    sample_feat = c("carbon","cell_num","class"), 
    taxon_rank = "Genus")

gseaRes_K
```

```{r}
gseaRes_K |> 
  filter(str_detect(pathway, "cell_num")) |>
  mutate(pathway = factor(pathway, levels = paste("cell_num", c(10,50,100,250),sep="_"))) |>
  gsea_plot()
```

```{r}
gseaRes_K |> 
  filter(str_detect(pathway, "carbon")) |>
  gsea_plot()
```

```{r}
gseaRes_K |> 
  filter(str_detect(pathway, "class")) |>
  gsea_plot()
```


