
# 共现网络的绘制以及相应参数的计算

## 加载需要的包

```{r, message=FALSE}
library(phyloseq)
library(tidyverse)
library(SpiecEasi)
library(ComplexHeatmap)
library(RColorBrewer)
library(ggpubr)
library(igraph)
library(dplyr)
library(stringr)
library(grDevices) 
library(rgexf) 
library(Matrix)
```

## 三种方式构建网络的差异

### 加载数据集

```{r}
physeq = readRDS("./data/dada2/microplate/filtered/physeq.rds") #读取
rename_asv <- function(physeq, prefix="ASV"){
  new_names <- paste0(prefix, seq_len(ntaxa(physeq)))
  taxa_names(physeq) <- new_names
  physeq}

physeq <- rename_asv(physeq, prefix="ASV")

physeq
```

## 构建互作网络

### 数据集清洗

```{r}
ps_final <- prune_taxa(taxa_sums(physeq) > 0, physeq)
```

### SLR方法构建网络

```{r}
se.slr.amgut <- spiec.easi(ps_final, method='slr', r=10, lambda.min.ratio=1e-4,
                           nlambda=50, pulsar.params=list(rep.num=50, ncores=1))
```

### 提取潜在变量和贡献计算

```{r}
X <- se.slr.amgut$est$data
L <- se.slr.amgut$est$resid[[getOptInd(se.slr.amgut)]]

pca <- robustPCA(X, L)

meta_df <- sample_data(ps_final) |> as_tibble() |> select(!contains("id"))
scores_mat <- pca$scores[, 1:10]

all_vars <- colnames(meta_df)
r2_matrix <- matrix(0, nrow = length(all_vars) + 1, ncol = 10, 
                    dimnames = list(c(all_vars, "carbon_x_cell_num"), paste0("PC", 1:10)))

for(i in 1:10) {
  current_pc <- scores_mat[, i]
  for(var in all_vars) {
    val <- meta_df[[var]]
    model_data <- if(is.numeric(val) || var == "cell_num") as.numeric(as.character(val)) else as.factor(val)
    
    if(length(unique(na.omit(model_data))) > 1) {
      adj_r2 <- summary(lm(current_pc ~ model_data))$adj.r.squared
      r2_matrix[var, i] <- max(0, adj_r2)
    }
  }
  
  fit_main  <- lm(current_pc ~ as.factor(carbon) + as.numeric(as.character(cell_num)), data = meta_df)
  fit_inter <- lm(current_pc ~ as.factor(carbon) * as.numeric(as.character(cell_num)), data = meta_df)
  
  delta_r2 <- summary(fit_inter)$adj.r.squared - summary(fit_main)$adj.r.squared
  r2_matrix["carbon_x_cell_num", i] <- max(0, delta_r2)
}

print(round(r2_matrix, 3))
```

## 潜变量数值矩阵理解

### 核心发现: PC5 是初始细胞数的最佳指示因子

```{r}
p = pheatmap::pheatmap(
  r2_matrix, 
  cluster_rows = F,  
  cluster_cols = FALSE,  
  angle_col = 0,         
  display_numbers = F, 
  number_color = "black", 
  fontsize_number = 10,  
  main = "Contribution of Environmental Factors (Adjusted R-squared)"
)

p
```

## 基于SLR算法的网络可视化

### 网络的构建

```{r}
group_low_abundance_taxa <- function(ps_final, n = 10, taxrank = "Genus", other_label = "other") {
  otu_sums <- taxa_sums(ps_final)
  top_taxa_names <- names(sort(otu_sums, decreasing = TRUE)[1:min(n, ntaxa(ps_final))])
  other_taxa_names <- taxa_names(ps_final)[!taxa_names(ps_final) %in% top_taxa_names]
  physeq_mod <- ps_final
  tt <- as(tax_table(physeq_mod), "matrix")
  tt[other_taxa_names, taxrank] <- other_label
  tax_table(physeq_mod) <- tax_table(tt)
  return(physeq_mod)
}

ps_grouped <- group_low_abundance_taxa(ps_final, n = 15, taxrank = "Genus")

print(ps_grouped)
```

### Gephi 可视化文件构建（去除非主网络的节点）

```{r}
library(rgexf) 

vertex_attr <- data.frame(tax_table(ps_grouped)) |> tibble::rownames_to_column("name")
refit_net <- as.matrix(getRefit(se.slr.amgut))
raw_icov <- as.matrix(se.slr.amgut$est$icov[[getOptInd(se.slr.amgut)]])

native_weight_mat <- -cov2cor(raw_icov)
diag(native_weight_mat) <- 0 
weighted_mat <- refit_net * native_weight_mat

ig2.mb <- adj2igraph(weighted_mat, vertex.attr = vertex_attr)
V(ig2.mb)$degree <- igraph::degree(ig2.mb)
g <- delete_vertices(ig2.mb, V(ig2.mb)[degree < 2]) 

E(g)$thickness   <- abs(E(g)$weight)
E(g)$interaction <- ifelse(E(g)$weight > 0, "Positive", "Negative")
g <- delete_edge_attr(g, "weight") 

g_pos <- subgraph_from_edges(g, E(g)[interaction == "Positive"], delete.vertices = FALSE)
g_neg <- subgraph_from_edges(g, E(g)[interaction == "Negative"], delete.vertices = FALSE)

V(g)$Degree_Total    <- igraph::degree(g)
V(g)$Degree_Positive <- igraph::degree(g_pos)
V(g)$Degree_Negative <- igraph::degree(g_neg)
V(g)$Pos_Neg_Ratio   <- V(g)$Degree_Positive / (V(g)$Degree_Negative + 0.001)

set.seed(123) 
V(g)$module <- as.numeric(membership(cluster_louvain(g, weights = E(g)$thickness)))

net_names_clean <- str_remove(V(g)$name, "^X\\.?")
tax_df <- as.data.frame(tax_table(ps_final))

V(g)$Phylum <- as.character(tax_df[net_names_clean, "Phylum"])
V(g)$Genus  <- as.character(tax_df[net_names_clean, "Genus"])
V(g)$Label  <- V(g)$name

raw_vals <- setNames(as.numeric(pca$loadings[5, ]), taxa_names(ps_final))
matched_scores <- raw_vals[net_names_clean]
if (all(is.na(matched_scores))) stop("stop")

V(g)$PC5_Score <- matched_scores

V(g)$Density_Class <- case_when(
  matched_scores < 0 ~ "High_Density",  
  matched_scores > 0 ~ "Low_Density",    
  TRUE ~ "Neutral"
)

V(g)$Density_Label <- paste0(V(g)$Density_Class, 
                             " (PC5 loading = ", 
                             round(V(g)$PC5_Score, 3), ")")

genus_colors <- readRDS("./data/dada2/microplate/top10_genus_colors.rds")
if (!"Other" %in% names(genus_colors)) genus_colors["Other"] <- "#DDDDDD"
matched_hex <- genus_colors[V(g)$Genus]
V(g)$color_hex <- ifelse(is.na(matched_hex), genus_colors["Other"], matched_hex)

node_df <- igraph::as_data_frame(g, what = "vertices")
edge_df <- igraph::as_data_frame(g, what = "edges")
nodes_meta <- node_df[, !colnames(node_df) %in% c("name", "Label", "color_hex"), drop = FALSE]
edges_meta <- edge_df[, !colnames(edge_df) %in% c("from", "to", "thickness"), drop = FALSE]

write.gexf(
  nodes = data.frame(id = node_df$name, label = node_df$Label),
  edges = edge_df[, c("from", "to")],
  edgesWeight = edge_df$thickness,
  nodesAtt = nodes_meta,
  edgesAtt = edges_meta,
  nodesVizAtt = list(
    color = cbind(t(col2rgb(node_df$color_hex)), a = 1.0),
    size = rep(20, vcount(g))
  ),
  output = "network_perfect_color.gexf"
)
```

